package com.genflowly.aicallerlib.models.gemini

import com.genflowly.aicallerlib.models.ProgrammingLanguage
import kotlinx.serialization.Serializable

/**
 * Code generated by the model that is meant to be executed, and the result returned to the model.
 * Source - https://ai.google.dev/api/caching#executablecode
 *
 * @param language Programming language of the code.
 * @param code The code to be executed.
 */
@Serializable
data class GeminiExecutableCode(
    val language: ProgrammingLanguage,
    val code: String
)
