package com.genflowly.aicallerlib.models.openai

import com.genflowly.aicallerlib.models.Message
import com.genflowly.aicallerlib.models.Role
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Represents a single message in the conversation.
 * Source - https://platform.openai.com/docs/api-reference/chat/create#chat-create-messages
 *
 * @param toolCalls The tool calls generated by the model, such as function calls.
 * @param refusal The refusal message generated by the model.
 * @param role The role of the message author. Can be "system", "user", or "assistant".
 * @param content The content of the message.
 *
 */

@Serializable
data class OpenAIMessageResponse(
    @SerialName("tool_calls") val toolCalls: List<OpenAIToolCall>? = null,
    val refusal: String? = null,
    override val role: Role,
    override val content: String?
): Message<String>()
