package com.genflowly.aicallerlib.models.openai

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Breakdown of tokens used in a completion.
 * Source - https://platform.openai.com/docs/api-reference/chat/object#chat/object-usage
 *
 * @param accepted_prediction_tokens When using Predicted Outputs, the number of tokens in the prediction that appeared in the completion.
 * @param audio_tokens Audio input tokens generated by the model.
 * @param reasoning_tokens Tokens generated by the model for reasoning.
 * @param rejected_prediction_tokens When using Predicted Outputs, the number of tokens in the prediction that did not appear in the completion. However, like reasoning tokens, these tokens are still counted in the total completion tokens for purposes of billing, output, and context window limits.
 */
@Serializable
data class OpenAICompletionTokenDetails(
    @SerialName("accepted_prediction_tokens") val acceptedPredictionTokens: Int,
    @SerialName("audio_tokens") val audioTokens: Int,
    @SerialName("reasoning_tokens") val reasoningTokens: Int,
    @SerialName("rejected_prediction_tokens") val rejectedPredictionTokens: Int
)
