package com.genflowly.aicallerlib.models.openai

import kotlinx.serialization.Serializable

/**
 * The tool calls generated by the model, such as function calls.
 * Source - https://platform.openai.com/docs/api-reference/chat/create#chat-create-messages
 *
 * @param id The ID of the tool call.
 * @param type The type of the tool. Currently, only function is supported.
 * @param function The function that the model called.
 */
@Serializable
data class OpenAIToolCall(
    val id: String,
    val type: String,
    val function: OpenAIFunction
)
