package com.genflowly.aicallerlib.models.openai
import com.genflowly.aicallerlib.models.Message
import com.genflowly.aicallerlib.models.Role
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Represents a single message in the conversation.
 * Source - https://platform.openai.com/docs/api-reference/chat/create#chat-create-messages
 *
 * @param name An optional name for the participant. Provides the model information
 * to differentiate between participants of the same role.
 * @param refusal The refusal message by the assistant.
 * @param toolCalls The tool calls generated by the model, such as function calls.
 * @param role The role of the messages author.
 * @param content The contents of the message.
 */
@Serializable
data class OpenAIMessageRequest(
    val name: String? = null,
    val refusal: String? = null,
    @SerialName("tool_calls") val toolCalls: OpenAIToolCall? = null,

    override val role: Role,
    override val content: String?
): Message<String>()
