package com.genflowly.aicallerlib.models

import kotlinx.serialization.Serializable

/**
 * The function that the model called.
 *
 * @param name The name of the function to call.
 * @param arguments The arguments to call the function with, as generated by the model in JSON format. Note that the model does not always generate valid JSON, and may hallucinate parameters not defined by your function schema. Validate the arguments in your code before calling your function.
 */
@Serializable
data class OpenAIFunction(
    val arguments: String,
    override val name: String
): Function()
