package com.genflowly.aicallerlib.models
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Represents a single message in the conversation.
 *
 * @param role The role of the message author. Can be "system", "user", or "assistant".
 * @param content The content of the message.
 * @param refusal The refusal message generated by the model.
 */
@Serializable
data class Message(
    val role: Role,
    val content: String? = null,
    val refusal: String? = null,
    @SerialName("tool_calls") val toolCalls: List<OpenAIToolCall>? = null
)
