package com.genflowly.aicallerlib.models
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Represents a single message in the conversation.
 *
 * @param name An optional name for the participant. Provides the model information
 * to differentiate between participants of the same role.
 * @param refusal The refusal message by the assistant.
 * @param toolCalls The tool calls generated by the model, such as function calls.
 */
@Serializable
data class OpenAIMessageRequest(
    val name: String? = null,
    val refusal: String? = null,
    @SerialName("tool_calls") val toolCalls: OpenAIToolCall? = null,

    override val role: Role,
    override val content: String?
): Message()
